services:
    Bigoen\Parasut\Services\:
        resource: '../../../../parasut/src/Services/*'
        arguments:
            $clientId: '%env(resolve:PARASUT_CLIENT_ID)%'
            $clientSecret: '%env(resolve:PARASUT_CLIENT_SECRET)%'
            $email: '%env(resolve:PARASUT_EMAIL)%'
            $password: '%env(resolve:PARASUT_PASSWORD)%'
            $companyId: '%env(resolve:PARASUT_COMPANY_ID)%'
            $httpClient: '@http_client'
